# Generated by Django 2.1.5 on 2019-01-13 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('t1health_app', '0002_auto_20190112_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='height',
        ),
        migrations.AddField(
            model_name='statistic',
            name='bmi',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='statistic',
            name='exercise',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='statistic',
            name='nutrition',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
