# Generated by Django 2.1.5 on 2019-01-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1health_app', '0003_auto_20190113_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthlyRevenue', models.CharField(max_length=50)),
                ('Month', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='statistic',
            name='bmi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='exercise',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='nutrition',
            field=models.IntegerField(),
        ),
    ]
