# Generated by Django 2.1.5 on 2019-01-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t1health_app', '0004_auto_20190113_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='author',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='date',
        ),
    ]
